---
- name: Ensure directory exists
  ansible.builtin.file:
    path: "{{ image_path }}"
    state: directory
    mode: '0755'

- name: Download images from URL
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ image_path }}/{{ item.name }}.{{ item.image_format}}"
    mode: '0644'
    force: false
    validate_certs: false
  loop: "{{ images_to_upload }}"
  loop_control:
    label: "{{ item.name }}"
  register: download_results

- name: Upload downloaded images to OpenStack
  openstack.cloud.image:
    auth: "{{ openstack_auth }}"
    name: "{{ item.name }}"
    filename: "{{ image_path }}/{{ item.name }}.{{ item.image_format}}"
    disk_format: "{{ item.disk_format }}"
    container_format: "{{ item.container_format }}"
    state: present
    wait: true
  loop: "{{ images_to_upload }}"
  loop_control:
    label: "{{ item.name }}"
  register: image_results

- name: Show uploaded images
  ansible.builtin.debug:
    msg: "Image {{ item.item.name }} uploaded successfully"
  loop: "{{ image_results.results }}"
