---
- name: Create OpenStack flavors
  openstack.cloud.compute_flavor:
    state: present
    auth: "{{ openstack_auth }}"
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    is_public: "{{ item.is_public }}"
  loop: "{{ flavors }}"
  register: flavor_result

- name: Debug flavor creation
  ansible.builtin.debug:
    msg: "Flavor {{ item.item.name }} created with ID: {{ item.id }}"
  loop: "{{ flavor_result.results }}"
  when: item.id is defined
